/// <reference types="node" />
import { By, WebDriver, WebElement } from 'selenium-webdriver';
import { BrowserCondition } from './conditions';
import { Collection } from './collection';
import { Configuration } from './configuration';
import { Element } from './element';
import { SearchContext } from './searchContext';
export declare class Browser implements SearchContext {
    readonly configuration: Configuration;
    private readonly wait;
    constructor(configuration?: Configuration);
    readonly driver: WebDriver;
    toString(): string;
    findWebElement(by: By): Promise<WebElement>;
    findWebElements(by: By): Promise<WebElement[]>;
    element(cssOrXpathOrBy: string | By): Element;
    all(cssOrXpathOrBy: string | By): Collection;
    should(condition: BrowserCondition, timeout?: number): Promise<Browser>;
    shouldNot(condition: BrowserCondition, timeout?: number): Promise<Browser>;
    waitUntil(condition: BrowserCondition, timeout?: number): Promise<boolean>;
    waitUntilNot(condition: BrowserCondition, timeout?: number): Promise<boolean>;
    matches(condition: BrowserCondition): Promise<boolean>;
    matchesNot(condition: BrowserCondition): Promise<boolean>;
    url(): Promise<string>;
    title(): Promise<string>;
    pageSource(): Promise<string>;
    screenshot(): Promise<Buffer>;
    executeScript(script: string | Function, ...args: any[]): Promise<{}>;
    readonly tabs: Promise<string[]>;
    readonly tabsNumber: Promise<number>;
    get(url: string): Promise<void>;
    resizeWindow(width: number, height: number): Promise<void>;
    closeCurrentTab(): Promise<void>;
    quit(): Promise<void>;
    nextTab(): Promise<void>;
    previousTab(): Promise<void>;
    switchToFrame(frameElement: Element): Promise<void>;
    switchToDefaultFrame(): Promise<void>;
    clearCacheAndCookies(): Promise<void>;
    private getAllWindowHandles;
}
