/// <reference types="node" />
import { By } from 'selenium-webdriver';
import { Collection } from './collection';
import { Condition } from './condition';
import { Driver } from './driver';
import { Element } from './element';
export declare namespace Actions {
    const click: (element: Element) => Promise<Element>;
    const contextClick: (element: Element) => Promise<Element>;
    function doubleClick(element: Element): Promise<Element>;
    function hover(element: Element): Promise<Element>;
    function pressKey(key: string): (element: Element) => Promise<any>;
    const pressEnter: (element: Element) => Promise<any>;
    const pressEscape: (element: Element) => Promise<any>;
    const pressTab: (element: Element) => Promise<any>;
    function scrollTo(element: Element): Promise<Element>;
    function sendKeys(value: string | number): (element: Element) => Promise<any>;
    function setValue(value: string | number): (element: Element) => Promise<any>;
    const visibility: (element: Element) => Promise<boolean>;
    const presence: (element: Element) => Promise<boolean>;
    const text: (element: Element) => Promise<any>;
    function attribute(attributeName: string): (element: any) => Promise<any>;
    const parent: (element: Element) => Element;
    function followingSibling(predicate?: string): (element: Element) => Element;
    function element(cssOrXpathOrBy: string | By): (searchContext: Element | Driver) => Element;
    function all(cssOrXpathOrBy: string | By): (searchContext: Element | Driver) => Collection;
    function filtered(condition: Condition<Element>): (collection: Collection) => Collection;
    function nth(index: number): (collection: Collection) => Element;
    const size: (collection: Collection) => Promise<number>;
    function find(condition: Condition<Element>): (collection: Collection) => Element;
    function open(url: string): (driver: Driver) => Promise<any>;
    function resizeWindow(width: number, height: number): (driver: Driver) => Promise<any>;
    const refresh: (driver: Driver) => Promise<any>;
    const acceptAlert: (driver: Driver) => Promise<any>;
    const url: (driver: Driver) => Promise<any>;
    const title: (driver: Driver) => Promise<any>;
    const pageSource: (driver: Driver) => Promise<any>;
    function executeScript(script: string | Function, ...args: any[]): (driver: Driver) => Promise<any>;
    const tabs: (driver: Driver) => Promise<any>;
    const nextTab: (driver: Driver) => Promise<any>;
    const previousTab: (driver: Driver) => Promise<any>;
    function switchToTab(tabId: string): (driver: Driver) => Promise<any>;
    function switchToFrame(frameElement: Element): (driver: Driver) => Promise<any>;
    const switchToDefaultFrame: (driver: Driver) => Promise<any>;
    const clearCacheAndCookies: (driver: Driver) => Promise<any>;
    function close(driver: Driver): Promise<any>;
    function quit(driver: Driver): Promise<any>;
    function screenshot(driver: Driver): Promise<Buffer>;
}
